### PR TITLE
debugging a local build producing an invalid jar due to incorrect exclusion of Guava

### PR DESCRIPTION
**Pull request by maxdeliso-da**
```
$ jar tf target/scala-2.12/authentication-service-assembly-0.1.jar  | grep com.google.common.base | grep Supplier
com/google/common/base/Functions$SupplierFunction.class
com/google/common/base/Supplier.class
com/google/common/base/Suppliers$ExpiringMemoizingSupplier.class
com/google/common/base/Suppliers$MemoizingSupplier.class
com/google/common/base/Suppliers$NonSerializableMemoizingSupplier.class
com/google/common/base/Suppliers$SupplierComposition.class
com/google/common/base/Suppliers$SupplierFunction.class
com/google/common/base/Suppliers$SupplierFunctionImpl.class
com/google/common/base/Suppliers$SupplierOfInstance.class
com/google/common/base/Suppliers$ThreadSafeSupplier.class
com/google/common/base/Suppliers.class
```

### CODE REVIEW

**Comment by rohanjr-da** [comment]
On my machine (MacOs Catalina)
```
java version "11.0.7" 2020-04-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.7+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.7+8-LTS, mixed mode)
```
I am building with
```
❯ rm -rf target && make clean build assembly
```
but the `grep` command for classes in the resulting jar is empty:
```
❯ jar tf target/scala-2.12/authentication-service-assembly-0.1.jar  | grep com.google.common.base
```
This gives an error when running the jar:
```
❯ java -jar target/scala-2.12/authentication-service-assembly-0.1.jar
[2020-07-10 13:18:09,739] [INFO] [akka.event.slf4j.Slf4jLogger] [authentication-service-system-akka.actor.default-dispatcher-4] - Slf4jLogger started
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/base/Supplier
	at io.grpc.internal.AbstractManagedChannelImplBuilder.<clinit>(AbstractManagedChannelImplBuilder.java:90)
	at com.daml.ledger.client.binding.LedgerClientBinding$.createChannel(LedgerClientBinding.scala:133)
	at com.projectdabl.authenticationservice.Main$.<init>(Main.scala:61)
	at com.projectdabl.authenticationservice.Main$.<clinit>(Main.scala)
	at com.projectdabl.authenticationservice.Main.main(Main.scala)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Supplier
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 5 more
```
I get the same error when running the same build steps on master.

**Comment by rohanjr-da** [comment]
When running the above build steps on master I appear to get the correct classes in the jar but the same error as above:
```
~/dev/ref-ledger-authenticator master
❯ jar tf target/scala-2.12/authentication-service-assembly-0.1.jar  | grep com.google.common.base | grep Supplier
org/checkerframework/com/google/common/base/Functions$SupplierFunction.class
org/checkerframework/com/google/common/base/Supplier.class
org/checkerframework/com/google/common/base/Suppliers$ExpiringMemoizingSupplier.class
org/checkerframework/com/google/common/base/Suppliers$MemoizingSupplier.class
org/checkerframework/com/google/common/base/Suppliers$SupplierComposition.class
org/checkerframework/com/google/common/base/Suppliers$SupplierFunction.class
org/checkerframework/com/google/common/base/Suppliers$SupplierFunctionImpl.class
org/checkerframework/com/google/common/base/Suppliers$SupplierOfInstance.class
org/checkerframework/com/google/common/base/Suppliers$ThreadSafeSupplier.class
org/checkerframework/com/google/common/base/Suppliers.class

~/dev/ref-ledger-authenticator master
❯ java -jar target/scala-2.12/authentication-service-assembly-0.1.jar
[2020-07-10 13:39:08,627] [INFO] [akka.event.slf4j.Slf4jLogger] [authentication-service-system-akka.actor.default-dispatcher-4] - Slf4jLogger started
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/base/Supplier
	at io.grpc.internal.AbstractManagedChannelImplBuilder.<clinit>(AbstractManagedChannelImplBuilder.java:90)
	at com.daml.ledger.client.binding.LedgerClientBinding$.createChannel(LedgerClientBinding.scala:133)
	at com.projectdabl.authenticationservice.Main$.<init>(Main.scala:61)
	at com.projectdabl.authenticationservice.Main$.<clinit>(Main.scala)
	at com.projectdabl.authenticationservice.Main.main(Main.scala)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Supplier
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 5 more
```

**Comment by garyverhaegen-da** [comment]
Problem seems to have been some interference from local caches (`~/.m2` or `~/.ivy2`); interestingly it happened to both @rohanjr-da and @cocreature, so presumably the issue may be some existing version used by some other project both had "recently" worked on. 🤷

**Comment by maxdeliso-da** [comment]
closing this as it was a bit of a straw-man and we identified the cause

**Pull request closed without merging**
